services:
  app:
    image: blog-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    container_name: blog-frontend-dev
  backend:
    image: blog-backend-dev   
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    container_name: blog-backend-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8080:80
    container_name: reverse-proxy-blog
    depends_on:
      - app
      - backend
volumes:
  frontend_node_modules:
  backend_node_modules:
    