services:
  app:
    image: blog-frontend
    build: ./frontend
    container_name: blog-frontend
  backend:
    image: blog-backend  
    build: ./backend
    env_file:
      - .env
    container_name: blog-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8080:80
    container_name: reverse-proxy-blog
    depends_on:
      - app
      - backend
    